require: rubocop-rspec

# increase line length since we are checking test files
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 120

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
 Max: 7

Metrics/BlockLength:
  Max: 200

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Max: 10