require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'temp/**/*'

# Line length is increased, since we are checking mostly selenium test files,
# which easily get longer and are still readable.
Layout/LineLength:
  Max: 120

# Block length is increased, since we are checking mostly selenium test files,
# which easily get longer and are still readable.
Metrics/BlockLength:
  Max: 700

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 150

# Describe class error is ignored since most of the tests in this suite will not test code,
# but rather UI functionality.
RSpec/DescribeClass:
  Exclude:
    - '**/*'

# Context wording is ignored since we test UI functionality not code.
RSpec/ContextWording:
  Exclude:
    - '**/*'

# We want to preserve labels for before/after blocks.
RSpec/BeforeAfterAll:
  Exclude:
    - '**/*'

# We want to preserve labels for before/after blocks.
RSpec/HookArgument:
  Exclude:
    - '**/*'

# Maximum nested group is increased for allowing more context separation between tests.
RSpec/NestedGroups:
  Max: 6

# Example length is increased due lot's of UI actions needed to be executed during test run.
# These increase test length significantly.
RSpec/ExampleLength:
  Max: 60

# Method length is increased due lot's of UI actions needed to be executed during test run.
# These increase test length significantly.
Metrics/MethodLength:
  Max: 15

# In some cases we must use instance variable, to pass state through the tests at the beginning and end of testing.
RSpec/InstanceVariable:
  Enabled: false

# Multiple expectations are allowed for now to speed up test execution.
RSpec/MultipleExpectations:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

# Selenium pageobjects are excluded from class documentation since they are self explanatory.
Style/Documentation:
  Exclude:
    - 'spec/support/pageobjects/**/*'

# Allow unicode in comments
Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true


# New rubocops
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Max: 20

Style/OptionalBooleanParameter:
  Enabled: false
